#!/usr/bin/env node
/**
 * REACTIVE deterministic codegen: App Spec JSON → Expo project on disk.
 * Usage: node scripts/codegen.mjs <spec.json> <outputDir> [--skip-install]
 */

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { spawnSync } from "child_process";
import Ajv2020 from "ajv/dist/2020.js";
import addFormats from "ajv-formats";
import { normalizeAppSpecForSchema } from "../apps/api/src/normalizeAppSpec.mjs";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function loadSpec(specPath) {
  const raw = fs.readFileSync(specPath, "utf8");
  return JSON.parse(raw);
}

function validateSpec(data) {
  const schemaPath = path.join(root, "docs", "spec-schema", "app-spec.schema.json");
  const schema = JSON.parse(fs.readFileSync(schemaPath, "utf8"));
  const ajv = new Ajv2020({ allErrors: true, strict: false });
  addFormats(ajv);
  const validate = ajv.compile(schema);
  if (!validate(data)) {
    console.error("App Spec validation failed:");
    for (const err of validate.errors ?? []) {
      console.error(`  ${err.instancePath || "(root)"} ${err.message}`);
    }
    process.exit(1);
  }
}

function shouldCopy(src) {
  const base = path.basename(src);
  if (base === "node_modules" || base === ".git") return false;
  return true;
}

function copyTemplate(destDir) {
  const srcDir = path.join(root, "template", "expo-starter");
  fs.mkdirSync(destDir, { recursive: true });

  function walk(from, to) {
    const st = fs.statSync(from);
    if (st.isDirectory()) {
      if (!shouldCopy(from)) return;
      fs.mkdirSync(to, { recursive: true });
      for (const name of fs.readdirSync(from)) {
        walk(path.join(from, name), path.join(to, name));
      }
    } else {
      fs.copyFileSync(from, to);
    }
  }

  for (const name of fs.readdirSync(srcDir)) {
    const fp = path.join(srcDir, name);
    if (!shouldCopy(fp)) continue;
    walk(fp, path.join(destDir, name));
  }
}

function esc(s) {
  return String(s)
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$");
}

const ICON_MAP = {
  calendar: "calendar",
  list: "list",
  chart: "bar-chart",
  settings: "cog",
  book: "book",
  add: "plus",
  home: "home",
  user: "user",
  code: "code",
};

function iconName(key) {
  if (!key) return "circle";
  return ICON_MAP[key] || key.replace(/[^a-z0-9-]/gi, "") || "circle";
}

function hexToRgb(hex) {
  const h = hex.replace("#", "");
  const n = parseInt(h, 16);
  return { r: (n >> 16) & 255, g: (n >> 8) & 255, b: n & 255 };
}

function mixRgb(a, b, t) {
  return {
    r: Math.round(a.r + (b.r - a.r) * t),
    g: Math.round(a.g + (b.g - a.g) * t),
    b: Math.round(a.b + (b.b - a.b) * t),
  };
}

function toHex({ r, g, b }) {
  const x = (n) => n.toString(16).padStart(2, "0");
  return `#${x(r)}${x(g)}${x(b)}`;
}

function buildColorsTs(spec) {
  const primary = spec.design.primary_color;
  const rgb = hexToRgb(primary);
  const tintForDarkMode = toHex(mixRgb(rgb, { r: 255, g: 255, b: 255 }, 0.28));

  return `// Generated by REACTIVE — edit constants/Colors.ts after export if needed.
const tintColorLight = '${primary}';
const tintColorDark = '${tintForDarkMode}';

export default {
  light: {
    text: '#111',
    background: '#fff',
    tint: tintColorLight,
    tabIconDefault: '#999',
    tabIconSelected: tintColorLight,
    primary: '${primary}',
  },
  dark: {
    text: '#f5f5f5',
    background: '#0a0a0a',
    tint: tintColorDark,
    tabIconDefault: '#666',
    tabIconSelected: tintColorDark,
    primary: '${primary}',
  },
};
`;
}

function buildTabsLayout(spec) {
  const routes = spec.navigation.routes;
  const initial = spec.navigation.initial_route;
  const ordered = [...routes].sort((a, b) => {
    if (a.id === initial) return -1;
    if (b.id === initial) return 1;
    return 0;
  });

  const screens = ordered
    .map(
      (r) => `      <Tabs.Screen
        name="${esc(r.id)}"
        options={{
          title: ${JSON.stringify(r.title)},
          tabBarIcon: ({ color }) => <TabBarIcon name="${iconName(r.icon)}" color={color} />,
        }}
      />`
    )
    .join("\n");

  return `import React from 'react';
import FontAwesome from '@expo/vector-icons/FontAwesome';
import { Tabs } from 'expo-router';

import Colors from '@/constants/Colors';
import { useColorScheme } from '@/components/useColorScheme';
import { useClientOnlyValue } from '@/components/useClientOnlyValue';

function TabBarIcon(props: {
  name: React.ComponentProps<typeof FontAwesome>['name'];
  color: string;
}) {
  return <FontAwesome size={28} style={{ marginBottom: -3 }} {...props} />;
}

export default function TabLayout() {
  const colorScheme = useColorScheme();

  return (
    <Tabs
      initialRouteName=${JSON.stringify(initial)}
      screenOptions={{
        tabBarActiveTintColor: Colors[colorScheme ?? 'light'].tint,
        headerShown: useClientOnlyValue(false, true),
      }}>
${screens}
    </Tabs>
  );
}
`;
}

function screensForRoute(spec, routeId) {
  return spec.screens.filter((s) => s.route_id === routeId);
}

function densityPadding(spec) {
  const d = spec.design.density;
  if (d === "compact") return 10;
  if (d === "spacious") return 24;
  return 16;
}

function buildTabScreen(spec, route) {
  const pad = densityPadding(spec);
  const matched = screensForRoute(spec, route.id);
  const blocks = (s) =>
    s.blocks.map((b) => `            <Text style={styles.chip}>${esc(b)}</Text>`).join("\n");

  const sections =
    matched.length > 0
      ? matched
          .map(
            (s) => `        <View style={styles.section}>
          <Text style={styles.screenTitle}>${esc(s.title)}</Text>
          <Text style={styles.purpose}>${esc(s.purpose)}</Text>
          <View style={styles.row}>
${blocks(s)}
          </View>
        </View>`
          )
          .join("\n")
      : `        <Text style={styles.purpose}>No screens linked to this tab yet. Set route_id in the App Spec.</Text>`;

  return `import { ScrollView, StyleSheet } from 'react-native';

import { Text, View } from '@/components/Themed';

export default function ${toComponentName(route.id)}Screen() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
${sections}
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: ${pad},
    paddingBottom: 32,
  },
  section: {
    marginBottom: 20,
  },
  screenTitle: {
    fontSize: 20,
    fontWeight: '700',
    marginBottom: 6,
  },
  purpose: {
    fontSize: 15,
    opacity: 0.85,
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  chip: {
    fontSize: 12,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 999,
    overflow: 'hidden',
    backgroundColor: 'rgba(120,120,120,0.15)',
  },
});
`;
}

function toComponentName(id) {
  return id
    .split(/[^a-zA-Z0-9]+/)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join("");
}

function orphanScreens(spec) {
  const routeIds = new Set(spec.navigation.routes.map((r) => r.id));
  return spec.screens.filter((s) => s.route_id && !routeIds.has(s.route_id));
}

function unlinkedScreens(spec) {
  return spec.screens.filter((s) => !s.route_id);
}

function buildGenerationNotes(spec, opts) {
  const orphans = orphanScreens(spec);
  const unlinked = unlinkedScreens(spec);
  const lines = [
    "# Generation notes",
    "",
    `App: **${spec.meta.name}** (\`${spec.meta.slug}\`) — spec \`${spec.meta.spec_version}\`.`,
    "",
    "## Assumptions",
    "",
    "- Deterministic REACTIVE codegen v1: tab navigation only; \`navigation.type\` must be \`tabs\`.",
    `- Theme uses \`design.primary_color\` ${spec.design.primary_color} for tab tint.`,
    "",
    "## Placeholders",
    "",
    "- UI blocks are labeled chips only; wire real lists/forms per product.",
    "- Auth/backend integrations are stubs unless you extend the template.",
    "",
  ];

  if (unlinked.length) {
    lines.push("## Screens without route_id", "");
    for (const s of unlinked) {
      lines.push(`- **${s.id}** (${s.title}) — not placed on a tab; add \`route_id\` or merge manually.`);
    }
    lines.push("");
  }

  if (orphans.length) {
    lines.push("## Invalid route_id references", "");
    for (const s of orphans) {
      lines.push(`- **${s.id}** references unknown route \`${s.route_id}\`.`);
    }
    lines.push("");
  }

  if (opts.skipInstall) {
    lines.push("## Build", "", "- `npm install` was skipped; run it in the project root before `expo start`.", "");
  }

  lines.push("---", "", "_Generated by REACTIVE codegen._", "");
  return lines.join("\n");
}

function patchAppJson(destDir, spec) {
  const p = path.join(destDir, "app.json");
  const j = JSON.parse(fs.readFileSync(p, "utf8"));
  j.expo.name = spec.meta.name;
  j.expo.slug = spec.meta.slug;
  j.expo.scheme = spec.meta.slug.replace(/-/g, "");
  j.expo.splash = j.expo.splash || {};
  j.expo.splash.backgroundColor = spec.design.primary_color;
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + "\n");
}

function patchPackageJson(destDir, spec) {
  const p = path.join(destDir, "package.json");
  const j = JSON.parse(fs.readFileSync(p, "utf8"));
  j.name = spec.meta.slug;
  fs.writeFileSync(p, JSON.stringify(j, null, 2) + "\n");
}

function writeSupabaseStub(destDir, spec) {
  if (spec.backend.mode !== "supabase-ready") return;
  const lib = path.join(destDir, "lib");
  fs.mkdirSync(lib, { recursive: true });
  const body = `/**
 * Supabase stub — wire @supabase/supabase-js when you add deps (see TEMPLATE.md allowlist + docs).
 * Env: EXPO_PUBLIC_SUPABASE_URL, EXPO_PUBLIC_SUPABASE_ANON_KEY
 */
export function getSupabaseClient() {
  const url = process.env.EXPO_PUBLIC_SUPABASE_URL;
  const key = process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY;
  if (!url || !key) {
    console.warn('[reactive] Supabase env not set; see .env.example');
    return null;
  }
  return null;
}
`;
  fs.writeFileSync(path.join(lib, "supabase.ts"), body);
}

function writeEnvExample(destDir, spec) {
  const lines = ["# Copy to .env and fill values", ""];
  if (spec.backend.mode === "rest" && spec.backend.base_url_placeholder) {
    lines.push(`${spec.backend.base_url_placeholder}=`);
  }
  if (spec.backend.mode === "supabase-ready") {
    lines.push("EXPO_PUBLIC_SUPABASE_URL=", "EXPO_PUBLIC_SUPABASE_ANON_KEY=");
  }
  lines.push("");
  fs.writeFileSync(path.join(destDir, ".env.example"), lines.join("\n") + "\n");
}

function main() {
  const specPath = process.argv[2];
  const outDir = process.argv[3];
  const skipInstall = process.argv.includes("--skip-install");

  if (!specPath || !outDir) {
    console.error("Usage: node scripts/codegen.mjs <spec.json> <outputDir> [--skip-install]");
    process.exit(1);
  }

  const absSpec = path.isAbsolute(specPath) ? specPath : path.join(process.cwd(), specPath);
  const absOut = path.isAbsolute(outDir) ? outDir : path.join(process.cwd(), outDir);

  let spec = loadSpec(absSpec);
  spec = normalizeAppSpecForSchema(spec);
  validateSpec(spec);

  if (spec.navigation.type !== "tabs") {
    console.error('codegen v1 only supports navigation.type "tabs" (normalize failed to coerce).');
    process.exit(1);
  }

  if (fs.existsSync(absOut) && fs.readdirSync(absOut).length > 0) {
    console.error(`Output directory must be empty: ${absOut}`);
    process.exit(1);
  }

  copyTemplate(absOut);

  const tabsDir = path.join(absOut, "app", "(tabs)");
  for (const f of ["index.tsx", "two.tsx"]) {
    const fp = path.join(tabsDir, f);
    if (fs.existsSync(fp)) fs.unlinkSync(fp);
  }

  fs.writeFileSync(path.join(absOut, "constants", "Colors.ts"), buildColorsTs(spec));
  fs.writeFileSync(path.join(tabsDir, "_layout.tsx"), buildTabsLayout(spec));

  for (const route of spec.navigation.routes) {
    fs.writeFileSync(path.join(tabsDir, `${route.id}.tsx`), buildTabScreen(spec, route));
  }

  patchAppJson(absOut, spec);
  patchPackageJson(absOut, spec);
  fs.writeFileSync(path.join(absOut, "GENERATION_NOTES.md"), buildGenerationNotes(spec, { skipInstall }));

  writeSupabaseStub(absOut, spec);
  writeEnvExample(absOut, spec);

  const genTs = path.join(absOut, "constants", "generatedSpec.ts");
  fs.writeFileSync(
    genTs,
    `/* eslint-disable */
// Frozen App Spec snapshot — do not edit by hand; regenerate from REACTIVE wizard.
export default ${JSON.stringify(spec, null, 2)} as const;
`
  );

  if (!skipInstall) {
    console.log("Running npm install in output…");
    const r = spawnSync("npm", ["install"], { cwd: absOut, stdio: "inherit", shell: process.platform === "win32" });
    if (r.status !== 0) {
      console.error("npm install failed. Fix errors above or re-run with --skip-install.");
      process.exit(1);
    }
  }

  console.log(`Done — Expo project at ${absOut}`);
  console.log("Next: cd into the folder && npx expo start");
}

main();
